name: Deploy to Home Server

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.APP_PATH }}
                      git pull origin main
                      npm install --production
                      export PATH=$PATH:/usr/local/bin  # PM2 경로 추가
                      pm2 --version || npm install -g pm2  # PM2 설치 확인 및 설치
                      pm2 restart ${{ secrets.PM2_APP_NAME }}
