name: Deploy to Home Server

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      nvm use 22
                      export PATH=$PATH:/home/first/.nvm/versions/node/v22.18.0/bin
                      cd ${{ secrets.APP_PATH }}
                      git pull origin main
                      npm install --omit=dev
                      /home/first/.nvm/versions/node/v22.18.0/bin/pm2 --version || npm install -g pm2 --prefix ~/.npm-global
                      /home/first/.nvm/versions/node/v22.18.0/bin/pm2 restart ${{ secrets.PM2_APP_NAME }}
