name: Deploy to Home Server

on:
    push:
        branches: [main] # 푸시할 브랜치 (필요 시 다른 브랜치로 변경 가능)

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.APP_PATH }}
                      git pull origin main
                      npm install --production
                      pm2 restart ${{ secrets.PM2_APP_NAME }}
